# Generated by Django 5.2.7 on 2025-12-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='session_key',
            field=models.CharField(max_length=40, verbose_name='セッションID'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='session_key',
            field=models.CharField(max_length=40, verbose_name='セッションID'),
        ),
    ]
