"""
Django settings for seijinphoto project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os


# ========================================
# 基本パス設定
# ========================================
# プロジェクトルートを基準に各種パスを組み立てる
BASE_DIR = Path(__file__).resolve().parent.parent


# ========================================
# セキュリティ / 環境変数
# ========================================
# 本番環境では環境変数から取得する想定
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-CHANGE_ME")
if not SECRET_KEY:
    raise RuntimeError("DJANGO_SECRET_KEY is not set")


# ========================================
# デバッグ設定
# ========================================
# ローカル確認時は True を想定
# 本番運用時は False を想定
DEBUG = True


# ========================================
# ホスト設定
# ========================================
# 環境変数があればそれを優先し、未設定時はローカル用を使用

#_allowed = os.getenv("DJANGO_ALLOWED_HOSTS", "")
#if _allowed:
#    ALLOWED_HOSTS = [h.strip() for h in _allowed.split(",") if h.strip()]
#else:
#    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

#一時的に広めに許可（あとで正式ドメインに絞る）
ALLOWED_HOSTS = ["*"]

# ========================================
# 本番運用時のセキュリティ設定
# ※ 現在はローカル確認のため無効化
# ========================================
'''
# ===== Security (behind nginx) =====
# nginx などのリバースプロキシの背後で動かすときに、
# HTTPS 判定や HSTS ヘッダ付与のために使用

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# HTTPS 強制
SECURE_SSL_REDIRECT = os.getenv("DJANGO_SECURE_SSL_REDIRECT", "True").lower() == "true"

# Cookie を HTTPS のときだけ送信
SESSION_COOKIE_SECURE = os.getenv("DJANGO_SESSION_COOKIE_SECURE", "True").lower() == "true"
CSRF_COOKIE_SECURE = os.getenv("DJANGO_CSRF_COOKIE_SECURE", "True").lower() == "true"

# POST時のCSRF対策で必要
CSRF_TRUSTED_ORIGINS = [
    "https://2kumi-seijin-party.com",
]

# HSTS（最初は短めの秒数で設定）
SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_SECURE_HSTS_SECONDS", "60"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", "False").lower() == "true"
SECURE_HSTS_PRELOAD = os.getenv("DJANGO_SECURE_HSTS_PRELOAD", "False").lower() == "true"
'''


# ========================================
# ローカル確認用セキュリティ設定
# ========================================
# 仮想環境・ローカル確認用に HTTPS 関連設定を無効化
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_HSTS_SECONDS = 0


# ========================================
# アプリケーション定義
# ========================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'photos',
]


# ========================================
# ミドルウェア
# ========================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ========================================
# URL / テンプレート / WSGI
# ========================================
ROOT_URLCONF = 'seijinphoto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'seijinphoto.wsgi.application'


# ========================================
# データベース
# ========================================
# 小規模イベント運用を想定して SQLite を使用
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ========================================
# パスワードバリデーション
# ========================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ========================================
# 言語 / タイムゾーン
# ========================================
LANGUAGE_CODE = 'ja'
TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True
USE_TZ = True


# ========================================
# 静的ファイル / アップロード画像
# ========================================
# CSS / JS / 静的アセット
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 投稿画像などのメディアファイル
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# ========================================
# Django デフォルト設定
# ========================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ========================================
# アプリ固有設定
# ========================================
# 管理者ページ用パスワード
ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD", "tama_admin")

# QRコードに埋め込む参加用キー
EVENT_JOIN_KEY = "abfh2-Af3wu-igi4hfGg"